# Generated by Django 3.0.6 on 2020-06-08 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Practice_Query', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='publisher',
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('book', models.ManyToManyField(related_name='details', to='Practice_Query.Book')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Practice_Query.Publisher')),
            ],
            options={
                'default_related_name': 'details',
            },
        ),
    ]
