# Generated by Django 3.0.6 on 2020-06-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Practice_Query', '0002_auto_20200608_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='book',
            new_name='books',
        ),
    ]
